### ISSUE TITLE
Emulate rotation of object

### ISSUE THREAD

**Issue by Padanian** [falahati/WinFormAnimation#2]
Hello. I'm following with much interest this repo. One thing it would be very nice to have is redrawing objects while rotating them. I know pictureboxes can't be rotated in winforms. In my case I have an emulated voltmeter with indicator gauge that needs to be redrawn when value changes. What I do is to redraw the control. It would be nice if I can have the gauge as a picturebox and animate the rotation around the pivot.

**Comment by falahati** [comment]
Hey,

This is a library to animate values compatible with WinForm. However it is not a transformation library and therefore there is no function or method to rotate, scale or transform a control in any way.

To be honest, I tried writing one for you, but this ended up so much more complicated than I anticipated at first and it was going to be a very big project. A lot of Message translation and management to be able to correctly pass through events like click, mouseover, and such. Windows Messages are not easily expandable and that's exactly why MS switched to WPF and XAML and wrote a new engine entirely on top of WinMessages.

Therefore, I ended up concluding that it is a waste of time. If you are writing a new application, just consider switching to XAML; otherwise, if you writing custom controls, you can always do these transformations by overriding the `OnPaint` method and then exposing a property for the transformation so **WinFormAnimation** can animate it.

In your specific case this should be quite easy if you have the source code of the control; and even if you don't, inheriting and then overring the `OnPaint` method is trivial if your custom control doesn't do much in regard to focus, mouse movement and such.

And in regard to redraw, **WinFormAnimation** doesn't do that for a very good reason. It eats so much resources and it is just wrong to expect **WinFormAnimation** to know when it should ask for redraw of a control; and even if **WinFormAnimation** expect something to change it doesn't know what part of screen going to change by changing am specific property and this is a problem as when invalidating a control we are supposed to be able to provide a region for invalidation. Therefore these type of actions should be handled by the control itself as it knows more about its own inner working. For example, if your custom control has a property named `BorderColor` it should invalidate itself and takes necessary actions each time this value changes.

However, if you can't edit the custom control and fix this problem where it should be, you can always use the custom invoker functions with this library and invalidate the control or redraw it after each change. Take a look at the `SafeInvoker` class and the overloads for animating a value using this class.

**Comment by falahati** [comment]
As an example of a custom `OnPaint` method, take a look at my other repo which is quite similar to yours. It does draw a circular progress bar and exposes multiple properties to customize its look. Controls like this are easy to animate because they handle everything else and the WinFormAnimation just need to change a property. In this specific user control, however; **WinFormAnimation** is embedded inside the code of the control, but this is not really necessary as you can animate any property even if the underlying control doesn't really support animation as long as there is a property for the transformation you desire.
https://github.com/falahati/CircularProgressBar

**Comment by Padanian** [comment]
Thanks, i'm in fact using onPaint already and it works. Thanks anyway for your effort.
